### ISSUE TITLE
Return JSON response with custom status code

### ISSUE THREAD

**Issue by ranyefet** [spirit-js/spirit#10]
Hello,

I'm building a JSON api using spirit.
I've started by adding catch-all route to return 404 response.

```javascript
route.get("*", {
  status: 404,
  headers: {
    'Content-Type': 'application/json'
  }
    body: JSON.stringify({
    message: 'Not Found',
  })
})
```

While it works, it's a little bit verbose. 

Is there a shorter way to do that, maybe something like:
```javascript
route.get("*", response.json(404, { message: "Not Found" }))
```

Thanks,
Ran.

**Comment by dodekeract** [comment]
Why don't you implement `response.json` like this?

```javascript
const response = {
	json: (status, body) {
		return {
			status,
			headers: {
				'Content-Type': 'application/json'
			},
			body
		};
	}
};
```

**Comment by hnry** [comment]
Hey @ranyefet ,

You can do `route.get("*", ...)` to catch GET only, or there is also `route.not_found(...)` which will 404 on every request regardless of method. (Ex: `route.not_found("Page is not found")` or `notFound` is camelCase alias to it.

You mentioned the explicit way, there's also @dodekeract suggestion. 

You also mentioned "response.json", there is a helper function similar to that:
```js
const {response} = require("spirit").node
const route = require("spirit-router")

const app = route.define([
  route.not_found(response(JSON.stringify({ message: "Not found" })).type("json")),
 // or
 route.get("*", response(JSON.stringify({ message: "Not found" })).type("json"))
])
```

Also this _should_ work (but it doesn't, so will need to fix):
```js
route.not_found({ message: "Not found" }) 
```
Which would do what you want. Will upload fix by tonight (spirit-router@0.4.0).

**Comment by ranyefet** [comment]
@dodekeract I know i can implement it by myself, but think it should be part of spirit it's really basic and a lot of users can benefit from helper like that.

@hnry Thanks for the suggestion but I prefer to not use `JSON.stringify` all over my code. Looking forward for the fix 👍

**Comment by dodekeract** [comment]
@ranyefet I think it should be a separate module. No need to pollute the core module with helper functions.

**Comment by hnry** [comment]
```js
route.not_found({ message: "Not found" }) 
// or for GET only requests
route.not_found("get", { message: "Not found" })
```
will produce a response with status code 404, and json content type header set, and a json body.

Also as per your suggestion @ranyefet I updated the `response` helper function to be:
```js
route.not_found(response({ message: "Not found" }).type("json"))
// or 
route.get("*", response({ message: "Not found" }).type("json").status_(404))
```

spirit v0.4.0 & spirit-router v0.4.0

Closing, if there's an issue or another suggestion feel free to let me know ✌️
