### ISSUE TITLE
A possible error in request documentation

### ISSUE THREAD

**Issue by gamtiq** [spirit-js/spirit#11]
It seems there is the following error in [request](https://github.com/spirit-js/spirit/blob/master/docs/request.md#dependency-injection) documentation:
```js
const hello = (url, method) => {
  return "Hello from " + method + " " + url
}
route.define([
  route.get("/", ["method", "url"], hello)
])
```
I suppose parameters of `hello` function should be `method, url`.

**Comment by hnry** [comment]
Good catch, thanks. PR welcomed in the future too!
