### ISSUE TITLE
Why did you not include the package-lock.json ?

### ISSUE THREAD

**Issue by andreGarvin** [spirit-js/spirit#18]
I just wanted to understand why you did not include the package-lock.json. Is it maybe you do not want to resolve any merge conflicts in the package-lock.json ( cause boi that shit is a nightmare ) if one does occur or you thought not really that necessary. I think it would be helpful to include that I or someone else does not accidentally install package that is not compatible with the packages on your local version of the project a version or a diff that might break the project.

Hope you have a great day or night 😄

**Comment by andreGarvin** [comment]
@hnry

**Comment by hnry** [comment]
Hey sorry for delayed reply... Basically I decided to use yarn over npm but never included the yarn lock file... I think it's weird to have 2 lock files committed in the end... So I ignored it. I think it should be ok for contributor who doesn't use yarn, there's very few dependencies spirit uses.

**Comment by andreGarvin** [comment]
Hey, @hnry I create this server-side render framework https://github.com/andreGarvin/teatime if you want to contribute check it out.

Also, I understand but I would say there is not a lot of direct dependencies but there is a ton of indirect dependencies.

Thanks for getting back to this issue thanks
