### ISSUE TITLE
Any ETA for RC version? 

### ISSUE THREAD

**Issue by peek4y** [spirit-js/spirit#7]

**Comment by hnry** [comment]
Hey @peek4y thanks for your interest, when all the remaining work in https://github.com/spirit-js/spirit/issues/2 are completed, it will be considered stable and more importantly I'll follow semver versioning more strictly.

Right now, 99% of everything you can do in Express (for example) is available to do now. It's only missing http2 support, http partial (range) support and etags.

But using things like body-parser, express-session, passport etc to add more functionality just like in Express is available right now.

What will probably hold off 1.0.0 release more than anything else is more docs, tutorials, and not missing features or anything like that.

**Comment by peek4y** [comment]
Thanks for the reply @hnry 

I know, there are stuff to be done, but, do you have any specific date (or in like a month or so?) in mind for the release? 

Can't wait to use this framework :smile:

**Comment by hnry** [comment]
I think around October I'll be finished with a web site, docs, full guides.

In around September, API is probably considered frozen / stable. 

As for the future beyond that (no timeline), if there is enough interest, I would like to bring spirit to the browser, and eventually also I would like to see a full featured framework be done based on spirit (but I wouldn't be doing it, it's more helping others who are interested).

**Comment by peek4y** [comment]
Sweet! Can't wait.

I really love the API design so far, great work :+1:  I'm definitely moving to spirit, and away from express.

Also, is there anyway to contribute? Any particular module etc.

**Comment by hnry** [comment]
Contributions are always very much appreciated, which brings up the point that I don't really have a clear way for someone to get into it...

Thanks for bringing that up 😄 , I'll try to get started on a wiki page mentioning how to get started better (will update this comment with a link later).

**Comment by peek4y** [comment]
Sweet! Thanks for the update.
