### ISSUE TITLE
optimise your .npmignore

### ISSUE THREAD

**Issue by Lichtjaeger** [spirit-js/spirit#8]
Hi,

great work. I like it.

But for package quality it would be nice if you optimise your `.npmignore`.

README and LICENSE should be in the package and CHANGELOG is OK.

But the _book, docs and spec directories blow up the package and the end user doesn't need a Makefile or CNAME (for example).

I could send you a PR but it's only a little change and you know best what you want to see if you look into `node_modules/spirit`.

**Comment by hnry** [comment]
@Lichtjaeger Sorry for late response, my laptop was being repaired last week. Thanks for bringing this up.
